//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobApply_Table
    {
        public int AppId { get; set; }
        public int UserId { get; set; }
        public int CompanyId { get; set; }
        public int JobId { get; set; }
        public string Resume { get; set; }
        public string Date { get; set; }
        public string Status { get; set; }
    }
}
